/**
 * Article data layer.
 *
 * - The lightweight index (articles-index.json) lists every article's metadata.
 *   The blog index page uses this and never loads article bodies.
 * - Full article bodies are loaded on demand via import.meta.glob, so each
 *   article ships as its own chunk.
 *
 * Both are generated by scripts/migrate-articles.mjs from the SEO master.
 */
import indexData from '../../content/articles-index.json';
import type { IntentId } from './intents';

export interface ArticleMeta {
  title: string;
  slug: string;
  category: string;
  subcategory?: string;
  intent: IntentId;
  topics: string[];
  published: string;
  meta_description: string;
  hero_image: string;
  word_count: number;
  article_number: number;
}

export interface ArticleFrontmatter extends ArticleMeta {
  source_verified: string;
  status: string;
  canonical_url: string;
  og_title: string;
  og_description: string;
}

export interface Article {
  frontmatter: ArticleFrontmatter;
  /** Markdown body, frontmatter stripped. */
  body: string;
}

/** All article metadata, newest first (the manifest is pre-sorted). */
export const ARTICLES: ArticleMeta[] = indexData as ArticleMeta[];

/**
 * Article bodies are eagerly globbed so they render synchronously, which keeps
 * the static-site prerender correct (the HTML contains the full article text).
 */
const rawArticles = import.meta.glob('../../content/articles/**/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;

/** Minimal YAML frontmatter parser. The format is controlled by the migration script. */
function parseFrontmatter(raw: string): { frontmatter: ArticleFrontmatter; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error('Article is missing frontmatter');
  const [, fmBlock, body] = match;
  const fm: Record<string, unknown> = {};
  for (const line of fmBlock.split('\n')) {
    const kv = line.match(/^([a-z_]+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rawValue] = kv;
    const value = rawValue.trim();
    if (value.startsWith('[')) {
      fm[key] = (value.slice(1, -1).match(/"((?:[^"\\]|\\.)*)"/g) || []).map((s) =>
        s.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\')
      );
    } else if (value.startsWith('"')) {
      fm[key] = value.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\');
    } else if (/^-?\d+$/.test(value)) {
      fm[key] = Number(value);
    } else {
      fm[key] = value;
    }
  }
  return { frontmatter: fm as unknown as ArticleFrontmatter, body: body.trim() };
}

/** Get a full parsed article by its URL slug. Returns null if not found. */
export function getArticle(slug: string): Article | null {
  const raw = rawArticles[`../../content/articles${slug}.md`];
  if (raw === undefined) return null;
  return parseFrontmatter(raw);
}

export function getArticleMeta(slug: string): ArticleMeta | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

/** Every article slug, for static-site route generation. */
export function allArticleSlugs(): string[] {
  return ARTICLES.map((a) => a.slug);
}

/**
 * Related articles for the "Explore more" rail: same intent first, then shared
 * topics, excluding the article itself. Falls back to newest if sparse.
 */
export function relatedArticles(slug: string, limit = 3): ArticleMeta[] {
  const self = getArticleMeta(slug);
  if (!self) return ARTICLES.slice(0, limit);
  const scored = ARTICLES.filter((a) => a.slug !== slug).map((a) => {
    let score = 0;
    if (a.intent === self.intent) score += 2;
    score += a.topics.filter((t) => t !== 'General' && self.topics.includes(t)).length;
    return { a, score };
  });
  scored.sort((x, y) => y.score - x.score);
  return scored.slice(0, limit).map((s) => s.a);
}
