/**
 * Article data layer.
 *
 * - The lightweight index (articles-index.json) lists every article's metadata.
 *   The blog index page uses this and never loads article bodies.
 * - Full article bodies are loaded on demand via import.meta.glob, so each
 *   article ships as its own chunk.
 *
 * Both are generated by scripts/migrate-articles.mjs from the SEO master.
 */
import indexData from '../../content/articles-index.json';
import type { IntentId } from './intents';

export interface ArticleMeta {
  title: string;
  slug: string;
  category: string;
  subcategory?: string;
  intent: IntentId;
  topics: string[];
  /** Industry (from title + slug) and agencies the body links to - scripts/lib/facets.mjs. */
  industries: string[];
  agencies: string[];
  /** Hand-curated by an editor in frontmatter; absent means false. */
  required_by_law?: boolean;
  published: string;
  meta_description: string;
  hero_image: string;
  word_count: number;
  article_number: number;
}

export interface ArticleFrontmatter extends ArticleMeta {
  source_verified: string;
  status: string;
  canonical_url: string;
  og_title: string;
  og_description: string;
}

export interface Article {
  frontmatter: ArticleFrontmatter;
  /** Markdown body, frontmatter stripped. */
  body: string;
}

/** All article metadata, newest first (the manifest is pre-sorted). */
export const ARTICLES: ArticleMeta[] = indexData as ArticleMeta[];

/**
 * Every article is served under /guides/<category>/<slug>. The slug in the index keeps its
 * historical shape (/<category>/<slug>) because the content files, the hero images and the
 * facet derivation all key on it; only the URL carries the prefix. The old paths 301 here in
 * vercel.json, so an article's URL is built by this function and nowhere else.
 */
export const GUIDES_PREFIX = '/guides';
export function articleUrl(slug: string): string {
  return `${GUIDES_PREFIX}${slug}`;
}

/** The category segments that exist in the corpus - the set the redirect rule must cover. */
export const ARTICLE_CATEGORIES: string[] = [...new Set(ARTICLES.map((a) => a.slug.split('/')[1]))];

/** Rewrite an in-body internal link (/<category>/<slug>) to its served URL. Others pass through. */
export function internalHref(href: string): string {
  const seg = href.split('/')[1];
  return seg && ARTICLE_CATEGORIES.includes(seg) ? articleUrl(href) : href;
}

/**
 * Article bodies are loaded on demand: each markdown file is its own chunk.
 * The article route resolves loadArticle() before rendering, so the static
 * prerender still produces HTML containing the full article text.
 */
const rawArticles = import.meta.glob('../../content/articles/**/*.md', {
  query: '?raw',
  import: 'default',
}) as Record<string, () => Promise<string>>;

/** Minimal YAML frontmatter parser. The format is controlled by the migration script. */
function parseFrontmatter(raw: string): { frontmatter: ArticleFrontmatter; body: string } {
  // Tolerate CRLF: a Windows checkout with core.autocrlf hands this parser \r\n files, and an
  // LF-only match here killed every local dev server and SSG build on that platform.
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) throw new Error('Article is missing frontmatter');
  const [, fmBlock, body] = match;
  const fm: Record<string, unknown> = {};
  for (const line of fmBlock.split(/\r?\n/)) {
    const kv = line.match(/^([a-z_]+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rawValue] = kv;
    const value = rawValue.trim();
    if (value.startsWith('[')) {
      fm[key] = (value.slice(1, -1).match(/"((?:[^"\\]|\\.)*)"/g) || []).map((s) =>
        s.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\')
      );
    } else if (value.startsWith('"')) {
      fm[key] = value.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\');
    } else if (/^-?\d+$/.test(value)) {
      fm[key] = Number(value);
    } else {
      fm[key] = value;
    }
  }
  return { frontmatter: fm as unknown as ArticleFrontmatter, body: body.trim() };
}

/** Load and parse a full article by its URL slug. Returns null if not found. */
export async function loadArticle(slug: string): Promise<Article | null> {
  const loader = rawArticles[`../../content/articles${slug}.md`];
  if (!loader) return null;
  return parseFrontmatter(await loader());
}

export function getArticleMeta(slug: string): ArticleMeta | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

/** Every article slug, for static-site route generation. */
export function allArticleSlugs(): string[] {
  return ARTICLES.map((a) => a.slug);
}

/**
 * Related articles for the "Explore more" rail: same intent first, then shared
 * topics, excluding the article itself. Falls back to newest if sparse.
 */
export function relatedArticles(slug: string, limit = 3): ArticleMeta[] {
  const self = getArticleMeta(slug);
  if (!self) return ARTICLES.slice(0, limit);
  const scored = ARTICLES.filter((a) => a.slug !== slug).map((a) => {
    let score = 0;
    if (a.intent === self.intent) score += 2;
    score += a.topics.filter((t) => t !== 'General' && self.topics.includes(t)).length;
    return { a, score };
  });
  scored.sort((x, y) => y.score - x.score);
  return scored.slice(0, limit).map((s) => s.a);
}
