#!/usr/bin/env node
/**
 * check-claims.mjs - REGRESSION GATE for the regulatory position.
 *
 * WHY THIS EXISTS. On 2026-08-23 a full pass removed 861 false "COVA is an introducer under
 * MAS Notice FAA-N02" assertions, every MAS-registration claim, every unbounded pricing promise
 * and 44 promises of a renewal-reminder feature that does not exist. That pass took a day and
 * read every article in the corpus. It must never be necessary again.
 *
 * A snapshot inventory goes stale the moment someone edits a file. This does not: it runs on
 * every build and FAILS THE BUILD if a banned self-claim comes back.
 *
 * THE ONE DISTINCTION THAT MAKES THIS USABLE - SELF-CLAIM vs EDITORIAL.
 * An article ABOUT MAS Notice FAA-N02 is correct editorial content and must never be flagged.
 * A footer saying COVA is MAS-registered is a false self-claim. A line only counts when
 * COVA/Covarage is its SUBJECT, or it is written in the first person. Without that test the
 * MAS patterns alone match ~1,600 lines of legitimate editorial.
 *
 * Usage:  node scripts/check-claims.mjs [--verbose]
 * Exit 0 = clean. Exit 1 = a banned self-claim is present; the build must not ship.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const VERBOSE = process.argv.includes('--verbose');

const SKIP_DIRS = new Set(['node_modules', 'dist', '.git', '.vite-react-ssg-temp', 'coverage']);
const EXTS = ['.md', '.mdx', '.tsx', '.ts', '.jsx', '.js', '.html', '.txt', '.json'];

/**
 * Files that document the rules themselves, so they quote the banned strings on purpose.
 * CLAIM_REGISTRY.md is generated by this very script and prints every rule's reason text, so
 * without this exemption the tool fails on its own output.
 */
const RULE_DOCS = new Set(['CLAUDE.md', 'README.md', 'HANDOVER.md', 'AGENTS.md', 'CLAIM_REGISTRY.md']);

/**
 * COVA must be the SUBJECT for a line to be a self-claim.
 *
 * The first draft listed specific verbs after "we" and specific nouns after "our". Breaking the
 * checker on purpose showed it silently missed "we match you" and "our concierge team" - two of
 * the exact claims this run removed. Any first-person subject counts now.
 */
const SELF = /\b(COVA|Covarage)\b|\bwe\s+\w+|\bour\s+\w+|\bus\b/i;

/**
 * Each rule: what it forbids, and why. `re` must match the SELF test too before it counts.
 * Keep the reason short - it is printed at the failure and is the only context the next
 * developer gets.
 */
const RULES = [
  { id: 'MAS-REGISTERED',
    re: /\b(?:COVA|Covarage|we)\b[^.\n]{0,80}?\b(?:is|are)\s+registered\s+(?:with|as an introducer)\b|MAS[-\s]registered\s+introducer|\bMAS INTRODUCER\b/i,
    why: 'MAS does not register introducers. COVA is never "MAS-registered" or "registered with MAS".' },

  { id: 'FAA-N02-SELF-CLAIM',
    re: /\b(?:COVA|Covarage)\b[^.\n]{0,60}?\b(?:is|acts as|operates as|operates under|appointed as|appointed under)\b[^.\n]{0,40}?(?:introducer|FAA-N02)|we (?:act|are) (?:as )?an introducer/i,
    why: 'No executed FAA-N02 introducer appointment exists. Do not assert one without a signed appointment.' },

  // selfRequired:false - these strings only ever describe COVA's own pricing on a COVA surface.
  // Gating them on a subject test made the checker miss a bare "Free 14-day trial, then S$9/mo."
  { id: 'UNBOUNDED-FREE', selfRequired: false,
    re: /always free|free for every company|free[-\s]to[-\s]use\s+(?:platform|insurance)|will never charge|no trial that expires|\bno subscription\b|no platform fees|no per-lead fees/i,
    why: 'Pricing must stay adjustable. Use "Free while in early access" - never an unbounded promise.' },

  { id: 'STALE-PRICE', selfRequired: false,
    re: /S?\$\s?9\s*\/?\s*(?:mo\b|month|pm\b)|14[-\s]day trial/i,
    why: 'The S$9/mo and 14-day-trial position is dead.' },

  { id: 'RENEWAL-REMINDERS',
    re: /(?:automated |timely )?renewal reminders|reminds? you before[^.\n]{0,30}laps|reminders at 60, 30/i,
    why: 'No scheduler, cron or reminder job exists. Say "every renewal date visible in one place".' },

  { id: 'MATCHING-SUITABILITY',
    re: /\bwe match (?:you|them|to)\b|matched to your industry|we route the lead|priority matching|(?:who|that) can match (?:a policy|cover) to your/i,
    why: 'COVA does not assess suitability or decide who a client sees. It passes requirements on.' },

  { id: 'MARKET-ACCESS',
    re: /shops the entire market|access to all insurers|\bthe full market\b|most competitive option|\bbest (?:deal|match)\b/i,
    why: 'COVA cannot deliver or substantiate a market-access or best-outcome claim.' },

  // The subject must be followed DIRECTLY by the verb. An earlier draft allowed 50 characters of
  // slack and fired on "COVA does NOT arrange insurance" - the correct sentence - 12 times.
  // A negated statement is the fix, never the defect.
  { id: 'COVA-AS-INTERMEDIARY',
    re: /\b(?:COVA|Covarage)\s+(?:will |can |may |also )?(?:binds?|arranges?|underwrites?|places?)\s+(?:the |your |any )?(?:cover|policy|policies|insurance)\b|policies you bind through/i,
    why: 'COVA does not arrange, bind, place or underwrite. Licensed intermediaries do.' },

  { id: 'IASO-AS-OURS',
    re: /our concierge team|our booking page|our health screening/i,
    why: 'Medical concierge is IASO Pte. Ltd., a separate related-party company. Attribute it.' },

  // Added after batch E. The GHS article gave nine named insurers merit adjectives and told the
  // reader "the right answer is" twice - once in the blockquote that feeds FAQPage results.
  { id: 'INSURER-RANKING', selfRequired: false,
    re: /the right answer is|\b(?:typically|clearly|usually) the better choice\b|\bstrong (?:hospital network|panel-doctor|domestic SME presence|PRUWorks)/i,
    why: 'COVA does not rank, rate or recommend a named insurer or product. State facts; let a licensed adviser judge.' },

  // Added after batch E. COVA holds no pricing data, so it cannot observe ranges or quote premium.
  { id: 'PREMIUM-DATA', selfRequired: false,
    re: /ranges observed on the COVA platform|observed on the (?:COVA|Covarage) platform|insurance for less than \$?[0-9]/i,
    why: 'COVA holds no pricing data and cannot quote or compare premium. A licensed adviser prices a placement.' },

  // Added 2026-08-24. The partner calculator paid share = pool * 0.80 while the ruled model passes
  // the introducer fee through WHOLESALE, so the live page understated our own offer by 20 percent
  // on every input. An arithmetic defect does not show up in a copy sweep, which is why this rule
  // reads the expression and not only the prose.
  { id: 'PARTNER-SHARE-SPLIT', selfRequired: false,
    re: /(?:^|[^A-Za-z])share\s*=\s*pool\s*\*|your share of the (?:referral|introducer) fee|\d{1,3}\s*(?:%|per ?cent)\s+of\s+the\s+(?:referral|introducer)\s+fee/i,
    why: 'No published partner share, split or multiplier. COVA takes a tiered processing fee out of the introducer fee and the scale is not set (Kong, 2026-08-24). Show the pool; promise no number.' },

  // Added 2026-08-24 on Kong's complaint that seats keep writing internal-memo language onto the
  // marketing site. This seat shipped a code comment naming him and a ruling date into a deck that
  // is served from the marketing domain and readable with view-source. Deliberately NARROW - it
  // matches internal artefact names only, never register or tone, because a tone rule would fire on
  // editorial and get widened until it means nothing. 'HONG KONG' is why bare KONG is not matched.
  { id: 'INTERNAL-MEMO-LEAK', selfRequired: false,
    re: /PENDING_KONG|COVA_RULINGS|FIX-SPEC-[AB]|KONG \d{4}-\d{2}-\d{2}|nodes\/(?:tm|cpo|coo|cd|cmo|cfo|cro|ux)\//,
    why: 'Internal governance artefacts do not belong in a served file. The build gate enforces a rule; a comment on the marketing site publishes it.' },
];

/** Exact approved strings. A line containing one of these is the fix, not the defect. */
const APPROVED = [
  'We are not a licensed insurance broker regulated by the Monetary Authority of Singapore',
  'we are not licensed or registered by the Monetary Authority of Singapore',
  'is not licensed or registered by the Monetary Authority of Singapore',
  'Free while in early access',
  'every renewal date visible in one place',
  'Every renewal date visible in one place',
];

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (EXTS.some(e => name.endsWith(e))) out.push(p);
  }
  return out;
}

const violations = [];
let scanned = 0;

for (const file of walk(ROOT)) {
  const rel = relative(ROOT, file).split(sep).join('/');
  const base = rel.split('/').pop();
  if (RULE_DOCS.has(base)) continue;            // these document the banned list on purpose
  if (rel.startsWith('scripts/check-claims')) continue;

  let text;
  try { text = readFileSync(file, 'utf8'); } catch { continue; }
  scanned++;
  if (text.length > 12_000_000) continue;

  const lines = text.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const isSelf = SELF.test(line);
    if (APPROVED.some(a => line.includes(a))) continue;
    for (const rule of RULES) {
      // editorial about third parties is not our claim, unless the pattern is inherently ours
      if (rule.selfRequired !== false && !isSelf) continue;
      if (rule.re.test(line)) {
        violations.push({ rel, line: i + 1, id: rule.id, why: rule.why, text: line.trim().slice(0, 160) });
      }
    }
  }
}

/**
 * --registry writes CLAIM_REGISTRY.md: the directory of WHERE the regulatory position and the
 * pricing position are actually stated in this repo. It is generated, never hand-edited, so it
 * cannot drift from the guard above. If the position changes, this is the list of files to touch
 * and nothing else needs re-reading.
 */
if (process.argv.includes('--registry')) {
  const SURFACES = [
    // NEEDLES MUST SURVIVE LINE WRAPPING. JSX prose is wrapped by the formatter, so the footer
    // reads "We are not a licensed insurance\n  broker regulated by...". A full-sentence needle
    // matched neither footer and the first registry silently omitted both.
    ['Regulatory position (the approved disclaimer)', [
      'not a licensed insurance', 'not licensed or registered']],
    ['Pricing position', ['Free while in early access']],
    ['Renewal wording (the feature that does NOT exist)', ['renewal date visible in one place', 'Renewal dates in one place']],
    ['Introduction wording', ['licensed insurance intermediary', 'licensed intermediary']],
    ['IASO / concierge attribution', ['IASO Pte. Ltd.', 'IASO']],
  ];
  const rows = new Map(SURFACES.map(([n]) => [n, []]));
  for (const file of walk(ROOT)) {
    const rel = relative(ROOT, file).split(sep).join('/');
    if (rel.startsWith('scripts/check-claims') || rel === 'CLAIM_REGISTRY.md') continue;
    let text; try { text = readFileSync(file, 'utf8'); } catch { continue; }
    const lines = text.split('\n');
    for (const [name, needles] of SURFACES) {
      for (let i = 0; i < lines.length; i++) {
        if (needles.some(n => lines[i].includes(n))) rows.get(name).push(`${rel}:${i + 1}`);
      }
    }
  }
  const out = [];
  out.push('# CLAIM REGISTRY - where the regulatory and pricing position is stated');
  out.push('');
  out.push('**GENERATED by `node scripts/check-claims.mjs --registry`. Never hand-edit.**');
  out.push('');
  out.push('This exists so nobody ever has to re-read the whole corpus again. On 2026-08-23 a full');
  out.push('pass removed 861 false FAA-N02 assertions, every MAS-registration claim, every unbounded');
  out.push('pricing promise and 44 promises of a renewal-reminder feature that does not exist.');
  out.push('');
  out.push('**To change the position, edit the files listed below and nothing else.** The guard in');
  out.push('`check-claims.mjs` runs on every build and fails it if a banned claim returns, so this');
  out.push('registry only has to answer "where is it stated", not "has it regressed".');
  out.push('');
  out.push('| Claim class | Where it is stated |');
  out.push('|---|---|');
  for (const [name, list] of rows) {
    const uniqFiles = [...new Set(list.map(x => x.split(':')[0]))];
    const shown = uniqFiles.length > 12
      ? uniqFiles.slice(0, 12).map(f => '`' + f + '`').join(', ') + ` and ${uniqFiles.length - 12} more`
      : (uniqFiles.map(f => '`' + f + '`').join(', ') || '_none in this repo_');
    out.push(`| **${name}** | ${shown} |`);
  }
  out.push('');
  out.push('## What the guard forbids');
  out.push('');
  out.push('| Rule | Why |');
  out.push('|---|---|');
  for (const r of RULES) out.push(`| \`${r.id}\` | ${r.why} |`);
  out.push('');
  out.push('## Not in this repo, and not fixable from it');
  out.push('');
  out.push('- **`cova-customer`** - the members app. Read-only to this lane. Its');
  out.push('  `request/config.ts` still carries "The platform is free for your business to use.');
  out.push('  COVA will never charge you." That is banned wording and belongs to the dev team.');
  out.push('- **The four loose decks at `d:/vault/Covarage/`** - not served by anything and not');
  out.push('  reachable from either site, but MAILABLE. Corrected by hand on 2026-08-23 (backup at');
  out.push('  `_loose_decks_backup_2026-08-23_pre-fix/`), and outside every fence, so no guard holds');
  out.push('  them. They can regress and nothing here would know.');
  out.push('');
  out.push('## The one corpus this registry CANNOT cover');
  out.push('');
  out.push('**`public/ig-content/` - 399 published Instagram PNGs.** The copy is rasterised into the');
  out.push('images and the source content bank does not exist anywhere in `D:/vault`, so no grep and no');
  out.push('guard can reach it. Sampled three, two defective: a premium price claim, and a');
  out.push('client-specific criminal-liability determination with profanity under the COVA logo. They');
  out.push('are served from the marketing domain and are `noindex, nofollow` via `vercel.json`, which');
  out.push('stops indexing and nothing else - they still return HTTP 200.');
  out.push('**Do not describe the published estate as reviewed while these stand.** -> `nodes/PENDING_KONG.md`');
  writeFileSync(join(ROOT, 'CLAIM_REGISTRY.md'), out.join('\n') + '\n', 'utf8');
  console.log('check-claims: wrote CLAIM_REGISTRY.md');
}

if (VERBOSE) console.log(`check-claims: scanned ${scanned} files under ${ROOT}`);

if (violations.length === 0) {
  console.log(`check-claims: ${scanned} files scanned, no banned self-claims. OK`);
  process.exit(0);
}

console.error(`\ncheck-claims: ${violations.length} BANNED SELF-CLAIM(S) FOUND\n`);
const byRule = new Map();
for (const v of violations) {
  if (!byRule.has(v.id)) byRule.set(v.id, []);
  byRule.get(v.id).push(v);
}
for (const [id, vs] of byRule) {
  console.error(`  [${id}] ${vs[0].why}`);
  for (const v of vs) console.error(`      ${v.rel}:${v.line}\n        ${v.text}`);
  console.error('');
}
console.error('These claims were removed on 2026-08-23 and must not return.');
console.error('If a hit is legitimate editorial, make COVA not the subject of the sentence,');
console.error('or add the exact approved wording. Do NOT widen a rule to make it pass.\n');
process.exit(1);
